.TH "md_src_docs_README" 3 "Sat Jul 6 2024" "Version 0.0.1" "LoongFlavors" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_src_docs_README \- 中华美食 C++ 库 

.SH "简介"
.PP
本库是一个基于 C++ 语言的美食库，提供了丰富的美食数据和相关功能。
.SH "安装"
.PP
.IP "1." 4
克隆本仓库到本地：
.PP
.SH "使用"
.PP
.IP "1." 4
导入 \fCFood\&.h\fP 文件：
.PP
.SH "贡献"
.PP
如果您发现了任何问题或有任何建议，请提交一个 issue 或 pull request。
.SH "许可证"
.PP
本库采用 MIT 许可证。 
